### Index
GET {{host}}/api/v1/payments
Authorization: Bearer {{token}}
Accept: application/json

### Store
POST {{host}}/api/v1/payments
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "payer_name": "test test",
  "payer_email": "test@test.com",
  "payer_address": "test",
  "amount": 123.45,
  "currency": "eur",
  "provider": "test"
}